spring.application.name=products
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

spring.datasource.url=jdbc:postgresql://localhost:5432/products
spring.datasource.username=liteThinking
spring.datasource.password=liteThinking.2026
spring.jpa.hibernate.ddl-auto=validate

app.jwt.secret=clave-secreta-temporal-cambiar-en-produccion-de-al-menos-256-bits
app.jwt.expiration=86400000

app.tasa.cop-usd=0.00026
app.tasa.cop-eur=0.00024
